# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-01-31 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('last_name', models.CharField(max_length=42)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='static/img/no-img.jpg', upload_to='static/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=42)),
                ('email', models.EmailField(max_length=75)),
                ('website', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='static/img/no-img.jpg', upload_to='static/img/')),
            ],
        ),
    ]
