# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-01-31 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_auto_20200201_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='static/img/field.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='static/img/field.jpg', upload_to='images/'),
        ),
    ]
