# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-02-03 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0007_auto_20200203_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='email',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=75, null=True),
        ),
    ]
