# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-02-10 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0008_auto_20200203_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='website',
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
