# Generated by Django 2.2.10 on 2020-03-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0009_auto_20200210_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='react_tag',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
